//
// Created by Alina Mihut on 11/7/19.
//

#ifndef FOOD_ORDERING_DEFINITIONS_H
#define FOOD_ORDERING_DEFINITIONS_H

#define MAX_FOOD_TYPE_NAME 10
#define MAX_TYPE_OF_FOOD_NAME 30
#define MAX_DRINK_NAME 20
#define MAX_CUTLERY_ANSWER_NAME 12
#define MAX_ADDITIONAL_INFO 30

#endif //FOOD_ORDERING_DEFINITIONS_H
